module.exports = {
  apps: [
    {
      name: "aeryn-api",
      script: "apps/api/routers/main.py",
      interpreter: "./venv-proot/bin/python",
      cwd: "/home/sen/aeryn-core-agent",
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        AERYN_MODE: "standalone",
        AERYN_PORT: "3010",
        AERYN_HOST: "127.0.0.1",
        PYTHONUNBUFFERED: "1",
        TZ: "Asia/Jakarta",
      },
      error_file: "logs/aeryn-api-error.log",
      out_file: "logs/aeryn-api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 20,
      min_uptime: "10s",
      restart_delay: 4000,
      wait_ready: true,
      kill_timeout: 5000,
      listen_timeout: 8000,
    },
    {
      name: "aeryn-dashboard",
      script: "aeryn_core/dashboard/run_server.py",
      interpreter: "./venv-proot/bin/python",
      cwd: "/home/sen/aeryn-core-agent",
      watch: false,
      max_memory_restart: "256M",
      env: {
        PYTHONPATH: "/home/sen/aeryn-core-agent",
        AERYN_DASHBOARD_PORT: "3020",
        AERYN_DASHBOARD_HOST: "127.0.0.1",
        PYTHONUNBUFFERED: "1",
        TZ: "Asia/Jakarta",
      },
      error_file: "logs/aeryn-dashboard-error.log",
      out_file: "logs/aeryn-dashboard-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 2000,
    },
  ],
};
