[package]
name = "aeryn-processor"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
aeryn-core = { path = "../aeryn-core" }
aeryn-splitter = { path = "../aeryn-splitter" }
serde = { workspace = true }
serde_json = { workspace = true }
regex = "1"
tracing = { workspace = true }
parking_lot = { workspace = true }

[lib]
name = "aeryn_processor"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
